name: Feature request
description: Propose an improvement
title: "[FEAT] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Business or user impact
